version: "3.8"
services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - mysql_db 
      - redis  # Add Redis as a dependency
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysqldata:/var/lib/mysql
    
  redis:
    image: redis:alpine
  celery:
    build: .
    # command: celery worker --app=pizzeria.celery --loglevel=info
    command: celery -A pizzeria.celery worker --pool=solo -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
  celery_beat:
    build: .
    # command: celery beat --app=pizzeria.celery --loglevel=info
    command: celery -A pizzeria.celery beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
    
volumes:
  mysqldata:
  
