# Generated by Django 4.2.5 on 2023-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'topping',
            },
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(choices=[(1, 'Thin-Crust'), (2, 'Normal'), (3, 'Cheese-Burst')], max_length=20)),
                ('cheese', models.CharField(choices=[(1, 'Cream Cheese'), (2, 'Mozzarella'), (3, 'Cheddar'), (4, 'Cottage cheese')], max_length=20)),
                ('order_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Accepted', max_length=20)),
                ('orderd_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('toppings', models.ManyToManyField(related_name='pizza_orders', to='api.topping')),
            ],
            options={
                'db_table': 'pizza_order',
            },
        ),
    ]
